    version: '3.8'
    services:
      postgres:
        image: postgres:13
        container_name: bookworm_db
        restart: always
        ports:
          - "5432:5432"
        environment:
          POSTGRES_USER: bookworm_user
          POSTGRES_PASSWORD: bookworm_password
          POSTGRES_DB: bookworm_db
        volumes:
          - postgres_data:/var/lib/postgresql/data
    
    volumes:
      postgres_data:
    